name: map_controller_plus
description: A map controller for Flutter map. Manage markers, lines and polygons.
homepage: https://github.com/TesteurManiak/map_controller_plus
repository: https://github.com/TesteurManiak/map_controller_plus
issue_tracker: https://github.com/TesteurManiak/map_controller_plus/issues
version: 4.0.0-dev.1
publish_to: none # Remove this line if you wish to publish to pub.dev
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map:
    git:
      url: https://github.com/fleaflet/flutter_map.git
      ref: 64e3a8e
  latlong2: ^0.9.0
  uuid: ^3.0.7

dev_dependencies:
  fd_lints: ^1.1.0
  flutter_test:
    sdk: flutter
  meta: ^1.9.1
  mocktail: ^0.3.0
